import { type JSX, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import type { PairingConfig } from "../../features/auth/types";
import { isValidSessionKey } from "../../features/auth/keyProof";
import { appConfig } from "../../app/appConfig";

export interface PairingScreenProps {
  errorMessage?: string;
  initialPairing?: PairingConfig;
  submitLabel?: string;
  onCancel?(): void;
  onPair(pairing: PairingConfig): void | Promise<void>;
}

export function PairingScreen({ errorMessage, initialPairing, submitLabel = "Pair Mac", onCancel, onPair }: PairingScreenProps): JSX.Element {
  const [relayUrl, setRelayUrl] = useState(initialPairing?.relayUrl ?? appConfig.defaultRelayUrl);
  const [deviceId, setDeviceId] = useState(initialPairing?.deviceId ?? "");
  const [key, setKey] = useState(initialPairing?.key ?? "");
  const [submitting, setSubmitting] = useState(false);

  async function submit(): Promise<void> {
    const trimmedKey = key.trim();
    if (!isValidSessionKey(trimmedKey)) {
      Alert.alert("Invalid key", "Enter the 32-character key generated by the Mac Agent.");
      return;
    }
    if (!relayUrl.trim() || !deviceId.trim()) {
      Alert.alert("Missing connection details", "Relay URL and device ID are required.");
      return;
    }

    setSubmitting(true);
    try {
      await onPair({
        relayUrl: relayUrl.trim(),
        deviceId: deviceId.trim(),
        key: trimmedKey,
      });
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <View style={styles.screen}>
      <Text style={styles.label}>Relay URL</Text>
      <TextInput
        autoCapitalize="none"
        autoCorrect={false}
        value={relayUrl}
        onChangeText={setRelayUrl}
        placeholder="wss://relay.company.example/mobile"
        placeholderTextColor="#66727c"
        style={styles.input}
      />

      <Text style={styles.label}>Mac Device ID</Text>
      <TextInput
        autoCapitalize="none"
        autoCorrect={false}
        value={deviceId}
        onChangeText={setDeviceId}
        placeholder="your-mac.local"
        placeholderTextColor="#66727c"
        style={styles.input}
      />

      <Text style={styles.label}>Temporary Key</Text>
      <TextInput
        autoCapitalize="none"
        autoCorrect={false}
        value={key}
        onChangeText={setKey}
        placeholder="32-character key"
        placeholderTextColor="#66727c"
        secureTextEntry
        style={styles.input}
      />

      {errorMessage ? <Text style={styles.error}>{errorMessage}</Text> : null}

      <Pressable disabled={submitting} style={[styles.primaryButton, submitting && styles.disabled]} onPress={submit}>
        <Text style={styles.primaryButtonText}>{submitting ? "Saving..." : submitLabel}</Text>
      </Pressable>
      {onCancel ? (
        <Pressable style={styles.secondaryButton} onPress={onCancel}>
          <Text style={styles.secondaryButtonText}>Cancel</Text>
        </Pressable>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    padding: 18,
    gap: 10,
  },
  label: {
    color: "#d7dde2",
    fontSize: 13,
    fontWeight: "600",
  },
  input: {
    minHeight: 48,
    borderColor: "#34424c",
    borderWidth: 1,
    borderRadius: 8,
    color: "#f5f7f8",
    paddingHorizontal: 12,
    backgroundColor: "#151c21",
  },
  primaryButton: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: "#30c48d",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
  },
  primaryButtonText: {
    color: "#08110d",
    fontWeight: "800",
    fontSize: 16,
  },
  disabled: {
    opacity: 0.55,
  },
  secondaryButton: {
    minHeight: 44,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#34424c",
    borderWidth: 1,
  },
  secondaryButtonText: {
    color: "#d7dde2",
    fontWeight: "700",
  },
  error: {
    color: "#ff8d8d",
    marginTop: 4,
  },
});
