import { type JSX, useCallback, useEffect, useRef, useState } from "react";
import {
  Alert,
  Linking,
  Modal,
  PermissionsAndroid,
  Platform,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import { Camera as CameraKitCamera, CameraType } from "react-native-camera-kit";

import { parsePairingLink } from "../../../../packages/protocol-ts/src/index.ts";
import type { PairingConfig } from "../../features/auth/types";
import { isValidSessionKey } from "../../features/auth/keyProof";
import { appConfig } from "../../app/appConfig";
import { Button, Card } from "../../ui/components";
import { colors, radii, spacing, typography } from "../../ui/theme";

type CameraKitReadCodeEvent = {
  nativeEvent: {
    codeStringValue?: string;
  };
};

export interface PairingScreenProps {
  errorMessage?: string;
  initialPairing?: PairingConfig;
  submitLabel?: string;
  onCancel?(): void;
  onPair(pairing: PairingConfig): void | Promise<void>;
}

export function PairingScreen({
  errorMessage,
  initialPairing,
  submitLabel = "Pair Mac",
  onCancel,
  onPair,
}: PairingScreenProps): JSX.Element {
  const [relayUrl, setRelayUrl] = useState(
    initialPairing?.relayUrl ?? appConfig.defaultRelayUrl,
  );
  const [deviceId, setDeviceId] = useState(initialPairing?.deviceId ?? "");
  const [key, setKey] = useState(initialPairing?.key ?? "");
  const [keyId, setKeyId] = useState(initialPairing?.keyId ?? "");
  const [scannerVisible, setScannerVisible] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    setRelayUrl(initialPairing?.relayUrl ?? appConfig.defaultRelayUrl);
    setDeviceId(initialPairing?.deviceId ?? "");
    setKey(initialPairing?.key ?? "");
    setKeyId(initialPairing?.keyId ?? "");
  }, [initialPairing]);

  async function submit(): Promise<void> {
    const trimmedKey = key.trim();
    if (!isValidSessionKey(trimmedKey)) {
      Alert.alert(
        "Invalid key",
        "Enter the 32-character key generated by the Mac Agent.",
      );
      return;
    }
    if (!relayUrl.trim() || !deviceId.trim()) {
      Alert.alert(
        "Missing connection details",
        "Relay URL and device ID are required.",
      );
      return;
    }

    setSubmitting(true);
    try {
      await onPair({
        relayUrl: relayUrl.trim(),
        deviceId: deviceId.trim(),
        key: trimmedKey,
        keyId: keyId.trim() || undefined,
      });
    } finally {
      setSubmitting(false);
    }
  }

  async function handleScannedPairing(pairing: PairingConfig): Promise<void> {
    if (!isValidSessionKey(pairing.key)) {
      Alert.alert("Invalid QR code", "The scanned pairing key is not valid.");
      return;
    }

    setRelayUrl(pairing.relayUrl);
    setDeviceId(pairing.deviceId);
    setKey(pairing.key);
    setKeyId(pairing.keyId ?? "");
    setScannerVisible(false);
    setSubmitting(true);
    try {
      await onPair(pairing);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <ScrollView
      keyboardShouldPersistTaps="handled"
      contentContainerStyle={styles.screen}
    >
      <Card success style={styles.scanCard}>
        <Text style={styles.scanEyebrow}>Recommended</Text>
        <Text style={styles.scanTitle}>Scan the Mac Agent QR code</Text>
        <Text style={styles.scanText}>
          Scan the QR code printed in the Mac Agent terminal. OmniWork will
          import the Relay URL, device ID, and temporary key automatically.
        </Text>
        <Button
          accessibilityLabel="Scan Mac Agent QR code"
          disabled={submitting}
          style={styles.scanButton}
          tone="primary"
          onPress={() => setScannerVisible(true)}
        >
          Scan in App
        </Button>
      </Card>

      <View style={styles.dividerRow}>
        <View style={styles.divider} />
        <Text style={styles.dividerText}>Manual fallback</Text>
        <View style={styles.divider} />
      </View>

      <Text style={styles.label}>Relay URL</Text>
      <TextInput
        autoCapitalize="none"
        autoCorrect={false}
        value={relayUrl}
        onChangeText={setRelayUrl}
        placeholder="wss://relay.company.example/mobile"
        placeholderTextColor="#66727c"
        style={styles.input}
      />

      <Text style={styles.label}>Mac Device ID</Text>
      <TextInput
        autoCapitalize="none"
        autoCorrect={false}
        value={deviceId}
        onChangeText={setDeviceId}
        placeholder="your-mac.local"
        placeholderTextColor="#66727c"
        style={styles.input}
      />

      <Text style={styles.label}>Temporary Key</Text>
      <TextInput
        autoCapitalize="none"
        autoCorrect={false}
        value={key}
        onChangeText={setKey}
        placeholder="32-character key"
        placeholderTextColor="#66727c"
        secureTextEntry
        style={styles.input}
      />

      {errorMessage ? <Text style={styles.error}>{errorMessage}</Text> : null}

      <Button
        disabled={submitting}
        style={styles.primaryButton}
        tone="primary"
        onPress={submit}
      >
        {submitting ? "Saving..." : submitLabel}
      </Button>
      {onCancel ? <Button onPress={onCancel}>Cancel</Button> : null}

      {scannerVisible ? (
        <PairingQrScannerModal
          visible={scannerVisible}
          onClose={() => setScannerVisible(false)}
          onScanned={handleScannedPairing}
        />
      ) : null}
    </ScrollView>
  );
}

function PairingQrScannerModal({
  visible,
  onClose,
  onScanned,
}: {
  visible: boolean;
  onClose(): void;
  onScanned(pairing: PairingConfig): void | Promise<void>;
}): JSX.Element {
  return (
    <CameraKitPairingQrScannerModal
      visible={visible}
      onClose={onClose}
      onScanned={onScanned}
    />
  );
}

function CameraKitPairingQrScannerModal({
  visible,
  onClose,
  onScanned,
}: {
  visible: boolean;
  onClose(): void;
  onScanned(pairing: PairingConfig): void | Promise<void>;
}): JSX.Element {
  const scanLockedRef = useRef(false);
  const [cameraPermissionGranted, setCameraPermissionGranted] = useState(false);
  const [cameraPermissionDenied, setCameraPermissionDenied] = useState(false);
  const [scanMessage, setScanMessage] = useState(
    "Point the camera at the Mac Agent QR code.",
  );

  useEffect(() => {
    if (!visible) {
      scanLockedRef.current = false;
      setScanMessage("Point the camera at the Mac Agent QR code.");
      return;
    }

    requestCameraPermission().then(({ granted, blocked }) => {
      setCameraPermissionGranted(granted);
      setCameraPermissionDenied(blocked || !granted);
      if (!granted) {
        setScanMessage(
          blocked
            ? "Camera permission is blocked. Open settings to enable scanning."
            : "Camera permission is required to scan the QR code.",
        );
      }
    });
  }, [visible]);

  const handleCodeRead = useCallback(
    (event: CameraKitReadCodeEvent) => {
      if (scanLockedRef.current) {
        return;
      }

      const scannedValue = event.nativeEvent.codeStringValue?.trim();
      if (!scannedValue) {
        return;
      }

      const pairing = parsePairingConfig(scannedValue);
      if (!pairing) {
        setScanMessage("This is not an OmniWork pairing QR code.");
        return;
      }

      scanLockedRef.current = true;
      setScanMessage("Pairing QR code detected. Connecting...");
      Promise.resolve(onScanned(pairing)).catch((error: unknown) => {
        scanLockedRef.current = false;
        setScanMessage(
          `Could not import QR code: ${formatErrorMessage(error)}`,
        );
      });
    },
    [onScanned],
  );

  return (
    <Modal
      animationType="slide"
      onRequestClose={onClose}
      presentationStyle="fullScreen"
      visible={visible}
    >
      <View style={styles.scannerScreen}>
        <View style={styles.scannerHeader}>
          <View style={styles.scannerHeaderText}>
            <Text style={styles.scannerTitle}>Scan Mac Agent QR</Text>
            <Text style={styles.scannerSubtitle}>
              Use the QR code printed in the Agent terminal.
            </Text>
          </View>
          <Pressable style={styles.scannerCloseButton} onPress={onClose}>
            <Text style={styles.scannerCloseText}>Close</Text>
          </Pressable>
        </View>

        <View style={styles.cameraPanel}>
          {cameraPermissionGranted ? (
            <>
              <CameraKitCamera
                allowedBarcodeTypes={["qr"]}
                cameraType={CameraType.Back}
                onReadCode={handleCodeRead}
                resizeMode="cover"
                scanBarcode
                scanThrottleDelay={1500}
                showFrame={false}
                style={StyleSheet.absoluteFill}
                torchMode="off"
              />
              <View pointerEvents="none" style={styles.scanFrame} />
            </>
          ) : (
            <View style={styles.cameraFallback}>
              <Text style={styles.cameraFallbackTitle}>
                {cameraPermissionDenied
                  ? "Camera permission needed"
                  : "Preparing camera"}
              </Text>
              <Text style={styles.cameraFallbackText}>
                {cameraPermissionDenied
                  ? "Allow camera access so OmniWork can scan the pairing QR code."
                  : "Initializing the camera scanner..."}
              </Text>
              <Button
                tone="primary"
                onPress={() => {
                  void requestCameraPermission().then(
                    ({ granted, blocked }) => {
                      setCameraPermissionGranted(granted);
                      setCameraPermissionDenied(blocked || !granted);
                      if (!granted && blocked) {
                        void openSystemSettings();
                      }
                    },
                  );
                }}
              >
                {cameraPermissionDenied ? "Allow Camera" : "Retry"}
              </Button>
            </View>
          )}
        </View>

        <Text style={styles.scannerHint}>{scanMessage}</Text>
      </View>
    </Modal>
  );
}

function parsePairingConfig(input: string): PairingConfig | null {
  const payload = parsePairingLink(input);
  if (!payload) {
    return null;
  }

  return {
    relayUrl: payload.relay_url,
    deviceId: payload.device_id,
    key: payload.key,
    keyId: payload.key_id,
  };
}

function formatErrorMessage(error: unknown): string {
  if (error instanceof Error && error.message) {
    return error.message;
  }
  if (typeof error === "string") {
    return error;
  }

  return "Unknown error";
}

async function requestCameraPermission(): Promise<{
  granted: boolean;
  blocked: boolean;
}> {
  if (Platform.OS !== "android") {
    return { granted: true, blocked: false };
  }

  const permission = PermissionsAndroid.PERMISSIONS.CAMERA;
  const hasPermission = await PermissionsAndroid.check(permission);
  if (hasPermission) {
    return { granted: true, blocked: false };
  }

  const status = await PermissionsAndroid.request(permission);
  return {
    granted: status === PermissionsAndroid.RESULTS.GRANTED,
    blocked: status === PermissionsAndroid.RESULTS.NEVER_ASK_AGAIN,
  };
}

async function openSystemSettings(): Promise<void> {
  await Linking.openSettings();
}

const styles = StyleSheet.create({
  screen: {
    flexGrow: 1,
    padding: spacing.xxl,
    gap: spacing.md,
  },
  scanCard: {
    padding: spacing.xl,
  },
  scanEyebrow: {
    color: colors.success,
    ...typography.eyebrow,
    letterSpacing: 0.7,
  },
  scanTitle: {
    color: colors.textPrimary,
    fontSize: 21,
    fontWeight: "800",
    marginTop: 6,
  },
  scanText: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginTop: spacing.sm,
  },
  scanButton: {
    minHeight: 46,
    marginTop: spacing.lg,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    marginVertical: 6,
  },
  divider: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
  },
  dividerText: {
    color: colors.textDim,
    ...typography.eyebrow,
    letterSpacing: 0.5,
  },
  label: {
    color: colors.textSecondary,
    ...typography.label,
  },
  input: {
    minHeight: 48,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.sm,
    color: colors.textPrimary,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.surface,
  },
  primaryButton: {
    minHeight: 48,
    marginTop: spacing.lg,
  },
  primaryButtonText: {
    color: colors.successText,
    ...typography.action,
    fontSize: 16,
  },
  disabled: {
    opacity: 0.55,
  },
  secondaryButton: {
    minHeight: 44,
    borderRadius: radii.sm,
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.border,
    borderWidth: 1,
  },
  secondaryButtonText: {
    color: colors.textSecondary,
    fontWeight: "700",
  },
  error: {
    color: colors.danger,
    marginTop: spacing.xs,
  },
  scannerScreen: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.xxl,
    gap: spacing.lg,
  },
  scannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.lg,
  },
  scannerHeaderText: {
    flex: 1,
  },
  scannerTitle: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "800",
  },
  scannerSubtitle: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  scannerCloseButton: {
    minHeight: 38,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.sm,
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  scannerCloseText: {
    color: colors.textSecondary,
    fontWeight: "800",
  },
  cameraPanel: {
    flex: 1,
    minHeight: 360,
    overflow: "hidden",
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    backgroundColor: "#050708",
  },
  cameraFallback: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    padding: spacing.xxl,
  },
  cameraFallbackTitle: {
    color: colors.textPrimary,
    fontSize: 17,
    fontWeight: "800",
    textAlign: "center",
  },
  cameraFallbackText: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  scanFrame: {
    position: "absolute",
    alignSelf: "center",
    top: "24%",
    width: "72%",
    aspectRatio: 1,
    borderColor: colors.success,
    borderRadius: radii.lg,
    borderWidth: 3,
  },
  scannerHint: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
});
