import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";
import webpack from "webpack";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, "..");
const workspaceRoot = path.resolve(appRoot, "..");
const requireFromApp = createRequire(path.join(appRoot, "package.json"));
const entryPath = path.join(appRoot, "src/editor/codeMirrorWebViewEntry.ts");
const tempDir = path.join(appRoot, ".generated/codemirror-webview");
const bundlePath = path.join(tempDir, "codemirror-editor.js");
const outputPath = path.join(appRoot, "src/editor/codeMirrorWebViewAssets.ts");

async function main() {
  await rm(tempDir, { force: true, recursive: true });
  await mkdir(tempDir, { recursive: true });
  await bundleCodeMirror();
  const source = await readFile(bundlePath, "utf8");
  const lines = [
    "// Generated by app/scripts/generateCodeMirrorWebViewAssets.mjs.",
    "// Do not edit by hand; update CodeMirror dependencies and rerun the generator.",
    "",
    `export const CODE_MIRROR_EDITOR_JS = ${JSON.stringify(source)};`,
    "",
  ];
  await writeFile(outputPath, lines.join("\n"), "utf8");
  await rm(tempDir, { force: true, recursive: true });
  console.log(`Generated ${path.relative(appRoot, outputPath)}`);
}

function bundleCodeMirror() {
  const compiler = webpack({
    mode: "production",
    target: ["web", "es2020"],
    entry: entryPath,
    output: {
      path: tempDir,
      filename: "codemirror-editor.js",
      iife: true,
    },
    resolve: {
      modules: [
        path.join(appRoot, "node_modules"),
        path.join(workspaceRoot, "node_modules"),
        "node_modules",
      ],
      extensions: [".ts", ".tsx", ".js", ".jsx", ".json"],
      symlinks: true,
    },
    resolveLoader: {
      modules: [
        path.join(appRoot, "node_modules"),
        path.join(workspaceRoot, "node_modules"),
        "node_modules",
      ],
    },
    module: {
      rules: [
        {
          test: /\.[jt]sx?$/,
          include: [appRoot, path.join(workspaceRoot, "packages")],
          use: {
            loader: "babel-loader",
            options: {
              presets: [requireFromApp.resolve("@react-native/babel-preset")],
              cacheDirectory: true,
            },
          },
        },
        {
          test: /\.m?js$/,
          resolve: {
            fullySpecified: false,
          },
        },
      ],
    },
    optimization: {
      minimize: true,
    },
  });

  return new Promise((resolve, reject) => {
    compiler.run((error, stats) => {
      compiler.close((closeError) => {
        if (error) {
          reject(error);
          return;
        }
        if (closeError) {
          reject(closeError);
          return;
        }
        if (stats?.hasErrors()) {
          reject(new Error(stats.toString({ colors: false, errors: true })));
          return;
        }
        resolve(undefined);
      });
    });
  });
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
