import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, "..");
const requireFromApp = createRequire(path.join(appRoot, "package.json"));

const assets = [
  {
    exportName: "XTERM_CSS",
    packageName: "@xterm/xterm",
    packageFile: "css/xterm.css",
  },
  {
    exportName: "XTERM_JS",
    packageName: "@xterm/xterm",
    packageFile: "lib/xterm.js",
  },
  {
    exportName: "FIT_ADDON_JS",
    packageName: "@xterm/addon-fit",
    packageFile: "lib/addon-fit.js",
  },
  {
    exportName: "WEB_LINKS_ADDON_JS",
    packageName: "@xterm/addon-web-links",
    packageFile: "lib/addon-web-links.js",
  },
];

const outputPath = path.join(appRoot, "src/terminal/xtermWebViewAssets.ts");

async function main() {
  const lines = [
    "// Generated by app/scripts/generateXtermWebViewAssets.mjs.",
    "// Do not edit by hand; update @xterm/* dependencies and rerun the generator.",
    "",
  ];

  for (const asset of assets) {
    const packageJsonPath = requireFromApp.resolve(`${asset.packageName}/package.json`);
    const packageRoot = path.dirname(packageJsonPath);
    const sourcePath = path.join(packageRoot, asset.packageFile);
    const source = await readFile(sourcePath, "utf8");

    lines.push(`// Source package: ${asset.packageName} ${asset.packageFile}`);
    lines.push(`export const ${asset.exportName} = ${JSON.stringify(source)};`);
    lines.push("");
  }

  await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
  console.log(`Generated ${path.relative(appRoot, outputPath)}`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
